"""
Send Outlook calendar invites for upcoming trustee sales.

Reads upcoming_sales.json (generated by update_foreclosure_dates.py)
and sends .ics calendar invites via email or Microsoft Graph API.

Setup options:
  Option A: Microsoft Graph API (requires Azure app registration)
    - Create app at https://portal.azure.com -> App registrations
    - Add Mail.Send and Calendars.ReadWrite permissions
    - Set MS_CLIENT_ID, MS_CLIENT_SECRET, MS_TENANT_ID in config.env

  Option B: SMTP (simpler, works with any email)
    - Set SMTP_SERVER, SMTP_PORT, SMTP_USER, SMTP_PASSWORD in config.env
"""
import json
import os
import sys
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from datetime import datetime, timedelta


def create_ics_event(address: str, apn: str, sale_date: str) -> str:
    """Create an .ics calendar event string."""
    dt = datetime.fromisoformat(sale_date.replace("Z", ""))
    start = dt.strftime("%Y%m%dT090000")
    end = dt.strftime("%Y%m%dT100000")
    # Reminder 1 day before and 1 hour before
    return f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sullivan Foreclosure//RealNex//EN
BEGIN:VEVENT
DTSTART:{start}
DTEND:{end}
SUMMARY:TRUSTEE SALE - {address}
DESCRIPTION:Trustee Sale for {address}\\nAPN: {apn}\\nSale Date: {sale_date[:10]}\\n\\nCheck RealNex CRM for full details.
LOCATION:{address}
BEGIN:VALARM
TRIGGER:-P1D
ACTION:DISPLAY
DESCRIPTION:Trustee Sale TOMORROW - {address}
END:VALARM
BEGIN:VALARM
TRIGGER:-PT1H
ACTION:DISPLAY
DESCRIPTION:Trustee Sale in 1 HOUR - {address}
END:VALARM
END:VEVENT
END:VCALENDAR"""


def send_via_smtp(to_email: str, subject: str, body: str, ics_content: str):
    """Send calendar invite via SMTP."""
    smtp_server = os.environ.get("SMTP_SERVER", "smtp.office365.com")
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    smtp_user = os.environ.get("SMTP_USER")
    smtp_pass = os.environ.get("SMTP_PASSWORD")

    if not smtp_user or not smtp_pass:
        print("ERROR: SMTP_USER and SMTP_PASSWORD required in config.env")
        return False

    msg = MIMEMultipart()
    msg["From"] = smtp_user
    msg["To"] = to_email
    msg["Subject"] = subject

    msg.attach(MIMEText(body, "plain"))

    # Attach .ics file
    ics_part = MIMEBase("text", "calendar", method="REQUEST")
    ics_part.set_payload(ics_content.encode())
    encoders.encode_base64(ics_part)
    ics_part.add_header("Content-Disposition", "attachment", filename="event.ics")
    msg.attach(ics_part)

    with smtplib.SMTP(smtp_server, smtp_port) as server:
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, to_email, msg.as_string())

    return True


def main():
    # Load config
    if os.path.exists("config.env"):
        with open("config.env") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    os.environ[key.strip()] = val.strip()

    # Load upcoming sales
    if not os.path.exists("upcoming_sales.json"):
        print("No upcoming_sales.json found. Run update_foreclosure_dates.py first.")
        sys.exit(1)

    with open("upcoming_sales.json") as f:
        sales = json.load(f)

    if not sales:
        print("No upcoming sales to send reminders for.")
        return

    notify_email = os.environ.get("NOTIFY_EMAIL", "matthew.sullivan@lee-associates.com")
    print(f"Sending {len(sales)} calendar reminders to {notify_email}")

    for sale in sorted(sales, key=lambda x: x["sale_date"]):
        address = sale["address"]
        apn = sale["apn"]
        sale_date = sale["sale_date"]

        subject = f"TRUSTEE SALE {sale_date[:10]} - {address}"
        body = (
            f"Upcoming Trustee Sale\n\n"
            f"Property: {address}\n"
            f"APN: {apn}\n"
            f"Sale Date: {sale_date[:10]}\n\n"
            f"Check RealNex CRM for full property details."
        )
        ics = create_ics_event(address, apn, sale_date)

        try:
            send_via_smtp(notify_email, subject, body, ics)
            print(f"  Sent: {sale_date[:10]} - {address}")
        except Exception as e:
            print(f"  FAILED: {address} - {e}")

            # Fallback: save .ics files locally
            safe_name = address.replace(" ", "_").replace(",", "")[:50]
            fname = f"calendar_{sale_date[:10]}_{safe_name}.ics"
            with open(fname, "w") as f:
                f.write(ics)
            print(f"  Saved as {fname} (import manually into Outlook)")


if __name__ == "__main__":
    main()
